language: java
sudo: false
cache: 
  directories: 
    - .cmakeify
    - ~/.gradle
matrix:
  include:
  - os: linux
    jdk: oraclejdk7
    script:
    - dpkg -l | grep gcc
    - ./gradlew assemble check
    - ./cmakeify
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6
deploy:
  provider: releases
  api_key:
    secure: UdnzVI6lMVQ0JX2m+zoXnq5DwAbj39+bz4xviRCpBE5LlijxFTNToMafxYPhK2cK26L6WZ5y8rkBMGAlOfsjwHHJjtc1EbywI+Wf88wdzQISHXU7qmwBopL6NxgtOoqnTTXYMnpd+8Efa7RRr23mirERPj7CZyM+eD67n8/vHkjqtUyNFw6FR0FHxzdeSkF95P4HyG1qlX7PqBNFSnCkW97+ypL5YNbQKJXlKTBfC7hoT/TlbmQNZcRiBcP6rXXgGx0ev8nMdf93RF3ucgc23bx7jbzS1wvEG0ULLEmPKN0d1pY949URXjMnkkAWMEpO73Yqoq9rX+L1uFghBN0N7T2/kFxbsFjidnFBBeBdl2mAZDwmR+Ovxeglft+NU2+eaLdQXFmf8lZqczu6fQrDXYvVC0C3UMYI+n6NNc4lkd+S5t7D7mV7ZoW2r5ggd78LsTLHpjzQ9FR2lui5PCQbWET+ardpmFQbjqaNF4swaKtMPivGzKbJXVWPTyea8TGtZEBArj0Vx05DTGIGa2CZTOVvMElnsTT21ZzJQ0VqLRDHGBvf2upbBfdK+iJ9KCOhsfv8wwi8xbrYYU9z9z/B8KwT0pbHNRbSbNzc4uW/ky441168xJL0GaNLxCQDr+6BQgJpm7cIkJ8zP2cLxVMchNQiUcHIYS++eun39HxFn1k=
  file:
  - build/libs/cmakeify-${TRAVIS_TAG}.jar
  - build/libs/cmakeify-${TRAVIS_TAG}-sources.jar
  - build/libs/cmakeify-${TRAVIS_TAG}-javadoc.jar
  skip_cleanup: true
  on:
    tags: true
